import CoreML
import CoreVideo
import Foundation

/// Raw output of one FastSAM forward pass, before any filtering.
struct RawPrediction {
    /// (37, N): 4 box + 1 score + 32 mask coefficients, per candidate.
    var det: MLMultiArray
    /// (32, H/4, W/4): prototype mask planes the coefficients weight.
    var proto: MLMultiArray
}

enum Inference {
    /// Compiled models are cached for the process's lifetime.
    ///
    /// Compiling a .mlpackage costs about as much as running it, and the app
    /// analyses one plate after another with the same model selected. The CLI
    /// gets the same benefit when it is handed a batch of images, which is why
    /// the verification harness passes them all to one process.
    private static var cache: [String: MLModel] = [:]
    private static let lock = NSLock()

    static func load(_ path: String) throws -> MLModel {
        lock.lock(); defer { lock.unlock() }
        if let m = cache[path] { return m }
        let cfg = MLModelConfiguration()
        // Compute unit made no measurable difference in Python (123 detections on
        // ANE, GPU and CPU alike), so this is chosen for speed, not for numerics.
        cfg.computeUnits = .all
        let url = URL(fileURLWithPath: path)
        // Xcode compiles any Core ML model it finds into .mlmodelc when it
        // copies it into an app bundle, so a bundled model is already compiled
        // and must not be compiled again. A .mlpackage on disk still must be.
        let compiled = url.pathExtension == "mlmodelc" ? url : try MLModel.compileModel(at: url)
        let model = try MLModel(contentsOf: compiled, configuration: cfg)
        cache[path] = model
        return model
    }

    /// Resolve a model by bare name against a directory, accepting either the
    /// packaged or the compiled form.
    static func load(dir: String, name: String) throws -> MLModel {
        let fm = FileManager.default
        for ext in ["mlmodelc", "mlpackage"] {
            let p = "\(dir)/\(name).\(ext)"
            if fm.fileExists(atPath: p) { return try load(p) }
        }
        throw AgarScope.AnalyzeError.modelsNotFound("\(dir)/\(name).mlpackage")
    }

    static func pixelBuffer(_ bmp: Bitmap) -> CVPixelBuffer? {
        var pb: CVPixelBuffer?
        let attrs = [kCVPixelBufferCGImageCompatibilityKey: true,
                     kCVPixelBufferCGBitmapContextCompatibilityKey: true] as CFDictionary
        guard CVPixelBufferCreate(nil, bmp.width, bmp.height,
                                  kCVPixelFormatType_32BGRA, attrs, &pb) == kCVReturnSuccess,
              let buf = pb else { return nil }
        CVPixelBufferLockBaseAddress(buf, [])
        defer { CVPixelBufferUnlockBaseAddress(buf, []) }
        guard let base = CVPixelBufferGetBaseAddress(buf) else { return nil }
        let stride = CVPixelBufferGetBytesPerRow(buf)
        let dst = base.assumingMemoryBound(to: UInt8.self)
        for y in 0..<bmp.height {
            let row = dst.advanced(by: y * stride)
            for x in 0..<bmp.width {
                let s = (y * bmp.width + x) * 4
                // Source is RGBA, CVPixelBuffer here is BGRA.
                row[x * 4 + 0] = bmp.rgba[s + 2]
                row[x * 4 + 1] = bmp.rgba[s + 1]
                row[x * 4 + 2] = bmp.rgba[s + 0]
                row[x * 4 + 3] = 255
            }
        }
        return buf
    }

    /// Every MLMultiArray a model returns, for callers that identify outputs by
    /// shape themselves. Same reasoning as run(): exported output names are
    /// autogenerated and not stable across re-exports.
    static func outputs(_ model: MLModel, image bmp: Bitmap) throws -> [MLMultiArray] {
        guard let pb = pixelBuffer(bmp) else { return [] }
        let name = model.modelDescription.inputDescriptionsByName.keys.first ?? "image"
        let input = try MLDictionaryFeatureProvider(dictionary: [name: MLFeatureValue(pixelBuffer: pb)])
        let out = try model.prediction(from: input)
        return out.featureNames.compactMap { out.featureValue(for: $0)?.multiArrayValue }
    }

    /// As above, for models whose input is a raw tensor rather than an image --
    /// CSRNet takes a normalised float array, not a pixel buffer.
    static func outputs(_ model: MLModel, tensor: MLMultiArray) throws -> [MLMultiArray] {
        let name = model.modelDescription.inputDescriptionsByName.keys.first ?? "x"
        let input = try MLDictionaryFeatureProvider(dictionary: [name: MLFeatureValue(multiArray: tensor)])
        let out = try model.prediction(from: input)
        return out.featureNames.compactMap { out.featureValue(for: $0)?.multiArrayValue }
    }

    static func run(_ model: MLModel, _ bmp: Bitmap) throws -> RawPrediction? {
        guard let pb = pixelBuffer(bmp) else { return nil }
        let name = model.modelDescription.inputDescriptionsByName.keys.first ?? "image"
        let input = try MLDictionaryFeatureProvider(dictionary: [name: MLFeatureValue(pixelBuffer: pb)])
        let out = try model.prediction(from: input)

        var det: MLMultiArray?
        var proto: MLMultiArray?
        for key in out.featureNames {
            guard let arr = out.featureValue(for: key)?.multiArrayValue else { continue }
            let s = arr.shape.map { $0.intValue }
            // Identify by shape rather than by name: exported output names are
            // autogenerated (var_909 and the like) and are not stable.
            if s.count == 3 && s[1] == 37 { det = arr }
            if s.count == 4 && s[1] == 32 { proto = arr }
        }
        guard let d = det, let p = proto else { return nil }
        return RawPrediction(det: d, proto: p)
    }
}
